{"name": "Ошибка при несуществующем номере заказа", "status": "passed", "description": "Проверка получения ошибки 404 при запросе с несуществующим номером трека", "steps": [{"name": "Отправка GET-запроса с несуществующим номером трека: 123123123", "status": "passed", "start": 1752420310051, "stop": 1752420310319}, {"name": "Проверка, что статус ответа равен 404", "status": "passed", "start": 1752420310319, "stop": 1752420310319}], "start": 1752420310051, "stop": 1752420310319, "uuid": "982358d3-d6c1-483b-8620-f092da7018d1", "historyId": "f6a508a3e2a358e6419ec4f0c26dceca", "testCaseId": "f6a508a3e2a358e6419ec4f0c26dceca", "fullName": "Tests.test_get_order_by_number.TestGetOrderByNumber#test_get_order_with_nonexistence_number", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_get_order_by_number"}, {"name": "subSuite", "value": "TestGetOrderByNumber"}, {"name": "host", "value": "DESKTOP-T2S04D8"}, {"name": "thread", "value": "8088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_get_order_by_number"}]}