{"name": "Ошибка при регистрации с уже существующим логином", "status": "passed", "description": "Проверка, что при повторной регистрации с тем же логином возвращается ошибка 409", "steps": [{"name": "Попытка регистрации с уже существующим логином", "status": "passed", "start": 1752420300894, "stop": 1752420301127}, {"name": "Проверка, что возвращается ошибка 409", "status": "passed", "start": 1752420301127, "stop": 1752420301127}], "attachments": [{"name": "log", "source": "86711ddc-6827-4c5f-975d-64c73114b556-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "cb8d59f8-af3c-4f6d-b0cb-29d763d8e5c1-attachment.txt", "type": "text/plain"}], "start": 1752420300894, "stop": 1752420301127, "uuid": "587c933d-3d9d-4058-93e0-1eec0e66823a", "historyId": "38925d1b0455ae737a2b0229c20cd801", "testCaseId": "38925d1b0455ae737a2b0229c20cd801", "fullName": "Tests.test_create_courier.TestCreateCourier#test_error_with_identical_login", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "DESKTOP-T2S04D8"}, {"name": "thread", "value": "8088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_create_courier"}]}